### ISSUE TITLE
Sonos http api on another server...

### ISSUE THREAD

**Issue by Snille** [CFenner/MagicMirror-Sonos-Module#16]
Hi, I'm running the sonos http api on another server "10.0.0.21" (used for other stuff as well).
But when I point to that server (apiBase: '10.0.0.21')

I get this in the console (on every update)...
SONOS_UPDATE
Failure: Error: Invalid protocol: 10.0.0.21:

Is the plugin not compatible anymore?

Best regards Snille

**Comment by CFenner** [comment]
Hi @Snille, you should use 'http://10.0.0.21' as apiBase. That should fix it.

**Comment by Snille** [comment]
Hi @CFenner, thank you. Now it almost "works" (or at least I only get the "SONOS_UPDATE" messages in the console. But on the mirror I only get "Loading music..." and nothing else. 
I did at first have the sonos api set on another port, but I changed that to the default 5005 one when it didn't work with the port after the IP at first. But still no luck... Config looks like this:
		{
		module: 'sonos',
		position: 'top_center',
		config: {
			apiBase: 'http://10.0.0.21'
			}
		},
Have I missed anything?

**Comment by CFenner** [comment]
You can also provide a port if necessary.

**Comment by Snille** [comment]
Hmm... I can't get it to work... Only get Loading music... on the mirror.
Tried both with and without the port on apiBase.
Anyway, for the moment I'm only testing things out, I'm not on the actual hardware yet. I'm going to install it all on a RPi later on. Maybe that's the reason? I'm running it now in an LXC with Ubuntu server 14.04.5 LTS. :)

**Comment by CFenner** [comment]
Can you debug and check the result of the Sonos update call? Do you get any results on http://10.0.0.21:5005/zones ?

**Comment by Snille** [comment]
Yepp, get all my zones...
clip: 
[{"uuid":"RINCON_000E583E62D201400","coordinator":{"uuid":"RINCON_000E583E62D201400","state":{"currentTrack":{"artist":"","title":"","album":"","albumArtUri":"","duration":0,"uri":"","type":"track","stationName":""},"nextTrack":{"artist":"","title":"","album":"","albumArtUri":"","duration":0,"uri":""},"volume":15,"mute":false,"trackNo":0,"elapsedTime":0,"elapsedTimeFormatted":"00:00:00","playbackState":"STOPPED","playMode":{"repeat":"none","shuffle":false,"crossfade":false}},"roomName":"Patio","coordinator":"RINCON_000E583E62D201400","groupState":{"volume":15,"mute":false}},"members":[{"uuid":"RINCON_000E583E62D201400","state":{"currentTrack":{"artist":"","title":"","album":"","albumArtUri":"","duration":0,"uri":"","type":"track","stationName":""},"nextTrack":......

**Comment by Vaggan** [comment]
I have the same problem. It looks like socketNotificationReceived does not get the notification after NodeHelper gets the data from the API and sends a new notification.
I have not looked at the module development since the changed how it works but I will see what I can do,

**Comment by CFenner** [comment]
Unfortunately I'm on vacation till next year and have no mirror with me ;) so no debugging possible at the moment..

**Comment by Vaggan** [comment]
I think i solved my problem today. It´s stupid...
I got the latest version of node-sonos-http-api and ran 'npm install' and 'npm start' and now it works.
Don´t think I made any other changes.

**Comment by Snille** [comment]
Hi again, now when it's all installed on my actual mirror hardware, it works. :) I'll probably ask some other stupid questions later on... :) 
Thank you.
